<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'AppBundle\Controller\StaffController' shared autowired service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\symfony\\src\\Symfony\\Bundle\\FrameworkBundle\\Controller\\ControllerTrait.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\symfony\\src\\Symfony\\Bundle\\FrameworkBundle\\Controller\\AbstractController.php';
include_once $this->targetDirs[3].'\\src\\AppBundle\\Controller\\StaffController.php';

$this->services['AppBundle\Controller\StaffController'] = $instance = new \AppBundle\Controller\StaffController();

$instance->setContainer(${($_ = isset($this->services['service_locator.yscbjmj']) ? $this->services['service_locator.yscbjmj'] : $this->load('getServiceLocator_YscbjmjService.php')) && false ?: '_'}->withContext('AppBundle\\Controller\\StaffController', $this));

return $instance;
