<?php

namespace AppBundle\Repository;

/**
 * staffRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class staffRepository extends \Doctrine\ORM\EntityRepository
{
    public function search($univ, $serv) {
        $q = $this->createQueryBuilder('s')
            ->where('s.university = :univ')
            ->andWhere('s.service = :serv OR s.job = :serv')
            ->setParameter('univ', $univ)
            ->setParameter('serv', $serv)
            ->getQuery();

        return $q->getResult();
    }
}
