<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8fotxgx\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8fotxgx/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container8fotxgx.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container8fotxgx\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container8fotxgx\appDevDebugProjectContainer([
    'container.build_hash' => '8fotxgx',
    'container.build_id' => 'f2273ae3',
    'container.build_time' => 1557687280,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8fotxgx');
