<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'argument_resolver.service' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Controller/ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Controller/ArgumentResolver/ServiceValueResolver.php';

return $this->services['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\ServiceLocator(['AppBundle\\Controller\\StaffController:SOSLoginPro' => function () {
    return ${($_ = isset($this->services['service_locator.9r1qt7y']) ? $this->services['service_locator.9r1qt7y'] : $this->load('getServiceLocator_9r1qt7yService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\StaffController:add' => function () {
    return ${($_ = isset($this->services['service_locator.vb8prsf']) ? $this->services['service_locator.vb8prsf'] : $this->load('getServiceLocator_Vb8prsfService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\StudentController:SOSInscription' => function () {
    return ${($_ = isset($this->services['service_locator.zblmzho']) ? $this->services['service_locator.zblmzho'] : $this->load('getServiceLocator_ZblmzhoService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\StudentController:SOSLogin' => function () {
    return ${($_ = isset($this->services['service_locator.qx07crr']) ? $this->services['service_locator.qx07crr'] : $this->load('getServiceLocator_Qx07crrService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\StudentController:SOSPasswordUpdate' => function () {
    return ${($_ = isset($this->services['service_locator.bplvum6']) ? $this->services['service_locator.bplvum6'] : $this->load('getServiceLocator_Bplvum6Service.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\StaffController::SOSLoginPro' => function () {
    return ${($_ = isset($this->services['service_locator.9r1qt7y']) ? $this->services['service_locator.9r1qt7y'] : $this->load('getServiceLocator_9r1qt7yService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\StaffController::add' => function () {
    return ${($_ = isset($this->services['service_locator.vb8prsf']) ? $this->services['service_locator.vb8prsf'] : $this->load('getServiceLocator_Vb8prsfService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\StudentController::SOSInscription' => function () {
    return ${($_ = isset($this->services['service_locator.zblmzho']) ? $this->services['service_locator.zblmzho'] : $this->load('getServiceLocator_ZblmzhoService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\StudentController::SOSLogin' => function () {
    return ${($_ = isset($this->services['service_locator.qx07crr']) ? $this->services['service_locator.qx07crr'] : $this->load('getServiceLocator_Qx07crrService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\StudentController::SOSPasswordUpdate' => function () {
    return ${($_ = isset($this->services['service_locator.bplvum6']) ? $this->services['service_locator.bplvum6'] : $this->load('getServiceLocator_Bplvum6Service.php')) && false ?: '_'};
}]));
