<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9lwu0rf\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9lwu0rf/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container9lwu0rf.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container9lwu0rf\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container9lwu0rf\appDevDebugProjectContainer([
    'container.build_hash' => '9lwu0rf',
    'container.build_id' => 'e99f1671',
    'container.build_time' => 1557612093,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9lwu0rf');
