<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXedabxe\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXedabxe/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerXedabxe.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerXedabxe\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerXedabxe\appDevDebugProjectContainer([
    'container.build_hash' => 'Xedabxe',
    'container.build_id' => 'fdab69d5',
    'container.build_time' => 1557621635,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXedabxe');
