<?php

namespace AppBundle\Repository;

/**
 * staffRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class staffRepository extends \Doctrine\ORM\EntityRepository
{
}
