<?php

namespace AppBundle\Repository;

/**
 * StaffCalendarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StaffCalendarRepository extends \Doctrine\ORM\EntityRepository
{
}
